import { defineConfig } from "vite";
import { resolve } from "node:path";

import { RACES } from "./race-page-meta.mjs";

export default defineConfig({
  base: "/tdf-analytics/",
  build: {
    outDir: "build",
    // Clear stale hashed chunks from previous builds; nothing hand-placed
    // lives in build/.
    emptyOutDir: true,
    // `rolldownOptions` is the Vite 8 name; Vite 8 replaced Rollup with
    // rolldown. The old `rollupOptions` STILL WORKS — checked on 2026-09-16 by
    // building with it, which emitted all six entry points and a byte-identical
    // bundle, with no deprecation warning. So this rename is forward-looking
    // hygiene, not a fix for anything currently broken. Worth knowing in both
    // directions: nobody needs to panic-rename on upgrade, and nobody should
    // assume the old key is doing nothing.
    rolldownOptions: {
      // Multi-page build: each race gets its own crawlable landing page
      // (generated by generate-race-pages.mjs, run as an npm "prebuild"
      // step) in addition to the main SPA shell at /.
      // Derived from the SAME object generate-race-pages.mjs writes from, so
      // adding a race can't produce a page that exists on disk but never
      // reaches build/. That is exactly what happened to classics/: dev served
      // it off disk so it looked fine, and only the deployed site 404'd on the
      // footer's /classics/ link.
      input: {
        main: resolve(__dirname, "index.html"),
        ...Object.fromEntries(
          Object.keys(RACES).map((race) => [race, resolve(__dirname, race, "index.html")]),
        ),
      },
    },
  },
});
