import { defineConfig } from "vite";
import { resolve } from "node:path";

export default defineConfig({
  base: "/tdf-analytics/",
  build: {
    outDir: "build",
    // Clear stale hashed chunks from previous builds; nothing hand-placed
    // lives in build/.
    emptyOutDir: true,
    rollupOptions: {
      // Multi-page build: each race gets its own crawlable landing page
      // (generated by generate-race-pages.mjs, run as an npm "prebuild"
      // step) in addition to the main SPA shell at /.
      input: {
        main: resolve(__dirname, "index.html"),
        tour: resolve(__dirname, "tour/index.html"),
        giro: resolve(__dirname, "giro/index.html"),
        vuelta: resolve(__dirname, "vuelta/index.html"),
      },
    },
  },
});
